---
configure_katello_organizations:
  - { name: Default Organization, state: present, manifest: sokeeffe-AWS }

configure_katello_lifecycle_environment:
  - name: Engineering
    organization: Default Organization
    prior: Library
    state: present
  - name: RC
    organization: Default Organization
    prior: Engineering
    state: present
  - name: Production
    organization: Default Organization
    prior: RC
    state: present

